//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD_EntitiyFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMP
    {
        public int EMPID { get; set; }
        public string ENAME { get; set; }
        public string DESIGNATION { get; set; }
        public Nullable<System.DateTime> DOJ { get; set; }
        public Nullable<decimal> SALARY { get; set; }
        public Nullable<int> DEPTNO { get; set; }
    }
}
